---
title: "MSDS 3606 - Assignment 4"
author: "Steven Millett"
date: "September 23, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br/>


###Question Segment 1 - Loading FiveThirtyEight Data:
<br/>
<!--This block is to install and load the fivethirtyeightpackge  -->
```{r loadfivethirtyeight, echo=TRUE}
#install.packages("fivethirtyeight")
library(fivethirtyeight)

```

<!-- Loads the fivethirtyeight package and loads the 18th data set college_recent_grads into the variable df. -->
```{r loadDataSet, echo=TRUE}
data(package = "fivethirtyeight")
df <- fivethirtyeight::college_recent_grads

```


<!-- This is to call the vignette of the fivethirtyeight package and reference the article this data appears in.-->
```{r checkURL, echo=TRUE}
#vignette("fivethirtyeight", package = "fivethirtyeight")


```
The URL is http://fivethirtyeight.com/features/the-economic-guide-to-picking-a-college-major/


<br/>
<!-- This outputs the names of the variables in df and the size of the data frame   -->
```{r loadNamesAndDimensions, echo=FALSE}
names(df)
dim(df)

```
###Question Segment 2 - Working with FiveThirtyEight Data:

<!-- This outputs the names of the variables in df and the number of columns   -->
```{r loadNamesAndColumnCount, echo=TRUE}
names(df)
ncol(df)

```

<!-- This populates the major count data frame with the unique values in df$major_category and counts the number of times that major appears in the vector. -->
```{r populateDataFrame, echo=TRUE}
major_count <- data.frame("Major_Category" = df$major_category,"Frequency"=1)
major_count <- aggregate(Frequency~Major_Category, data = major_count, sum)
```


<!-- This is to create a barplot from the data frame major_count. The function par is to format the barplot so it appears properly. The title function is used to format the Y label to move it closer to the barplot.  -->
```{r barPlot, echo=TRUE}
par(mar=c(5.5,15,4.5,2.5),mgp=c(3,1,0),las=2)
barplot(height = major_count$Frequency,main="Major by Category", names.arg = major_count$Major_Category, xlab = "Frequency", horiz=TRUE, xlim=c(0,30), col="blue")
title(ylab="Major",line=0)
```

<!-- This is to write major_count data frame to a CSV -->
```{r writeOutputToCSV, echo=TRUE}
write.csv(x=major_count,file="fivethirtyeight.csv",row.names = FALSE)

```
###Question Segment 3 - Github repository:

You can find all details on my github here:
https://github.com/stmillett/Homework 

